image: python:3.11.4-slim-buster

stages:
  - deploy

before_script:
  - python3 -V

deploy_job:
  stage: deploy
  only:
    - main
  script:
    - echo "Starting Deploy Job"
    - ssh $USER@$SERVER 'echo "Making project directory" && mkdir -p ~/projects/tgbots/stine'
    - ssh $USER@$SERVER 'echo "Pulling latest changes" && cd ~/projects/tgbots && git pull origin main'
    - ssh $USER@$SERVER 'echo "Installing requirements" && pip3 install -r ~/projects/tgbots/stine/requirements.txt'
    - ssh $USER@$SERVER 'echo "Killing any existing tmux sessions" && tmux kill-session -t tgstinebot || true'
    - ssh $USER@$SERVER 'echo "Exporting environment variables" && export STINE_API_HASH=$STINE_API_HASH && export STINE_API_ID=$STINE_API_ID && export STINE_API_TOKEN=$STINE_API_TOKEN'
    - ssh $USER@$SERVER 'echo "Creating new tmux session" && cd ~/projects/tgbots/stine && tmux new-session -d -s tgstinebot'
    - ssh $USER@$SERVER 'echo "Sending keys to tmux session" && cd ~/projects/tgbots/stine && tmux send-keys -t tgstinebot "python3 bot.py" C-m'
    - echo "Deploy job completed"